### ISSUE TITLE
Update Text

### ISSUE THREAD

**Issue by el-samiyel** [mdg-iitr/RotatingText#6]
How can I update the text of an existing rotatable?

**Comment by el-samiyel** [comment]
To elaborate, there seems to be no way to update the text. Am i missing something?

Good work btw, its very classy.

**Comment by harjot-oberai** [comment]
There is no way to update text inside a rotatable yet. The major issue with it will be calculating and changing the dimensions of the TextView displaying the rotating text, if these calculations are not done properly, then the transitions are not smooth as the dimensions keeps on changing eith the text being displayed. I will try to find a workaround to this limitation as soon as I get some time.
