### ISSUE TITLE
Add option to stop rotation after one cycle.

### ISSUE THREAD

**Issue by softmarshmallow** [mdg-iitr/RotatingText#7]
how do i disable auto slide feature from it??

i would like to slide only one cycle and the effect to be ended.

am i missing? or there is no fuctionality for that. 
or i should implement this by some stupid way (eg. disable the view)
??

**Comment by alikhaaki** [comment]
same issue

**Comment by softmarshmallow** [comment]
@dev-ritik please close the issue with comments

**Comment by dev-ritik** [comment]
@softmarshmallow this issue has been addressed in PR #28. We will add it in the next release of the library.
